# ================================================================
# 网站基础设置
# ================================================================

# 网站标题
title: "你的博客标题"
# 网站描述（用于SEO）
description: "分享我的技术学习和生活感悟"
# 网站标签行
tagline: "记录成长，分享知识"
# 网站关键词
keywords: "博客, 技术, 学习"

# ================================================================
# URL设置 - 针对 blog 仓库特别重要！
# ================================================================

# 网站完整URL（你的GitHub用户名）
url: "https://hdbuyer.github.io"
# 基础URL路径（必须设置为你的仓库名）
baseurl: "/blog"

# ================================================================
# Jekyll 设置
# ================================================================

# 主题设置（Chirpy主题）
theme: jekyll-theme-chirpy

# 永久链接格式
permalink: /posts/:title/
permalink_defaults: 
paginate: 10
paginate_path: /page:num/

# 时区设置
timezone: Asia/Shanghai

# 构建设置
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# ================================================================
# 个人信息
# ================================================================

author:
  name: "hdbuyer"
  email: "你的邮箱@example.com"  # 请修改为你的邮箱
  twitter: ""  # 你的Twitter用户名（可选）
  github: hdbuyer  # 你的GitHub用户名

# 头像设置
avatar: "/assets/img/avatar.jpg"  # 头像图片路径

# ================================================================
# 语言和本地化
# ================================================================

lang: zh-CN
# 或者英文：lang: en

# ================================================================
# 社交链接
# ================================================================

social:
  # 取消注释并填写你的社交账号
  # github: hdbuyer
  # twitter: your_twitter_id
  # facebook: your_facebook_id
  # linkedin: your_linkedin_id
  # stackoverflow: your_so_id  # 你的Stack Overflow用户ID
  # dribbble: 
  # behance: 
  # instagram: 
  # telegram: 
  # rss: /blog/feed.xml  # RSS订阅链接

# ================================================================
# 评论系统设置
# ================================================================

comments:
  active: ""  # 可选: giscus, utterances, disqus
  # 如果需要启用评论，请取消下面的注释并配置
  # giscus:
  #   repo: hdbuyer/blog
  #   repo_id: 
  #   category: 
  #   category_id: 
  #   mapping: pathname
  #   reactions_enabled: 1
  #   theme: light

# ================================================================
# 分析工具
# ================================================================

analytics:
  google: 
    # 取消注释并添加你的Google Analytics跟踪ID
    # id: "G-XXXXXXXXXX"
  facebook:
    # 取消注释并添加你的Facebook Pixel ID
    # app_id: 
    # pixels:

# ================================================================
# SEO 和网站验证
# ================================================================

seo:
  # 取消注释并添加你的验证代码
  # google_site_verification: 
  # bing_site_verification: 
  # baidu_site_verification: 
  # yandex_site_verification: 
  # naver_site_verification:

# ================================================================
# 网站外观和主题设置
# ================================================================

theme_mode: 
  # 可选值: 
  #   - "dark" # 始终深色模式
  #   - "light" # 始终浅色模式
  #   - "auto" # 跟随系统设置（默认）

# 主题色调
theme_color: auto
# 或者指定颜色: theme_color: "#4fa4ff"

# 代码高亮主题
highlight_theme: auto
# 可选: 
#   - "light" 
#   - "dark" 
#   - "auto"

# ================================================================
# 首页设置
# ================================================================

home_posts:
  # 首页显示类型
  type: recent  # 可选: recent, pinned
  # 置顶文章列表（当type为pinned时使用）
  pinned:

# ================================================================
# 分类和标签设置
# ================================================================

categories:
  - name: 技术
    description: "技术相关文章"
    color: "#4fa4ff"
  - name: 生活
    description: "生活感悟"
    color: "#f4a521"
  - name: 学习
    description: "学习笔记"
    color: "#34c85a"

# ================================================================
# 其他设置
# ================================================================

toc: true  # 是否在文章中显示目录

math: true  # 是否启用数学公式支持

mermaid: true  # 是否启用Mermaid图表支持

# 图片路径设置
img_cdn: ""  # 如果需要使用CDN，可以在这里设置

# 默认图片
default_image: "/assets/img/og-image.jpg"

# ================================================================
# 构建排除文件
# ================================================================

exclude:
  - "*.gem"
  - "*.gemspec"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules/"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"

# ================================================================
# 自定义变量
# ================================================================

# 这里可以添加你自己的自定义变量
custom:
  motto: "保持学习，持续进步"